site_name: OpenNMT
extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
docs_dir: tree

markdown_extensions:
  - math
  - sane_lists
  - def_list
  - fenced_code
pages:
  - Overview: index.md
